Add tests for not (monadic ~)
Dyalog/ullu pull request #90
Opened 2024-11-26 10:30 UTC by pmikkelsen

2025-01-17 09:15 UTC, pmikkelsen commented
This pull request adds tests for monadic ~ (not), but it also refactors `_RunVariations_` so *it* runs the model function, instead of the caller. In my opinion, this is the only correct thing to do, as the plan is to add more and more random "variations" of the tests to that operator, which requires that it can run the model and compare the result.

It also means it now becomes possible to pass data to `_RunVariations_` which results in errors being generated from the primitive and model function. The errors are compared, just like non-errors are compared.

This pull-request will break all other tests because they use `_RunVariations_` the old way, where the right argument contained the expected data as well, often computed as such `... RunVariations (d1 model d2) d1 d2`. The fix there is simply to remove `(d1 model d2)`, as it will be computed automatically. For monadic calls such as `... RunVariations (model data) data`, the fix is to change it to `... RunVariations ⊂data`.

A lot of tests pass explicitly computed "expected values" to `_RunVariations_`, which is in my opinion better handled by calls to `Assert`. RunVariations is not able to do anything meaningful with a model function, if the expected values are pre-computed.

2025-01-17 09:16 UTC, pmikkelsen commented
I see that auto-format in RIDE has caused all the changes to become a bit difficult to see. I apologise for that.

2025-01-17 09:26 UTC, pmikkelsen commented
The tests introduced in this pull-request requires the fix for mantis 21762 to be merged into the interpreter.

2025-01-20 13:41 UTC, sloorush commented
Thanks @pmikkelsen 

When would the fix for mantis 21762 be merged into the interpreter?

2025-01-30 08:56 UTC, pmikkelsen commented
> Thanks @pmikkelsen
> 
> When would the fix for mantis 21762 be merged into the interpreter?

The changes are ready (and quite simple), so we can do a diff together at some point and merge it in.

2025-02-06 14:30 UTC, pmikkelsen commented
Update @sloorush: the fix has now been merged into version 20.0 of the interpreter.

2025-02-21 08:17 UTC, sloorush requested changes
Sorry, it took a while for me to send a review. Thank you for the PR @pmikkelsen.

I do like the new approach with RunVariations, but we will have to rewrite all the old tests and I don't know if it is worth it to just let the old tests be with a legacy RunVariations functions and continue ahead or rewrite them? What do you think? This approach does make writing tests a lot faster.

@mkromberg Could you also please take a look at this new approach and let us know what you think? Because I remember we had a lot of reasons to keep non model tests, mostly because of correctness of models if multiple things break, but do you think this covers everything?

P.S. Reviewing APL code is hard 👀

2025-02-21 08:17 UTC, sloorush commented on unittest.apln
> +
Or you can probably just revert this file back if there are no changes

2025-02-21 08:17 UTC, sloorush commented on utils.apln
> +    change0sto1←{1@(0∘=)⍵}          ⍝ Replacing zeroes in ⍵ with 1
Can also be changed in one line instead of the entire file being diff-ed

2025-02-21 08:17 UTC, sloorush commented on tests/not.apln
> +                  r,←'Not (~)'desc quadparams RunVariations⊂data
Is it possible to add flags for the tests to skip the tests that don't work with versions<20.0. Was it a bug that was fixed later? Will the bug be fixed in 18.2 and 19.0?

2025-02-27 08:27 UTC, sloorush commented
@pmikkelsen, Did you check the code coverage of the tests?

If there is any dead code or code that needs coverage omitting there is Mantis#0019402 as an open issue which can be mentioned when making commits based on codecoverage

2025-03-04 14:25 UTC, definitelyprobably reviewed
I think it all looks good to me, but I may have missed something important... The PR  description rationale makes sense to me, at least.

2025-03-04 14:30 UTC, pmikkelsen commented on iso_defs.apln
> +    IntegerTolerance←1E¯14 ⍝ aka SYSFUZZ
Yes, comparison tolerance and integer tolerance is not the same thing. The ISO standard lists integer-tolerance as an implementation defined parameter, with the following definition:

![billede](https://github.com/user-attachments/assets/19e176ff-c2bf-42b1-b3df-c699981313f6)

Would you agree that integer tolerance is what we call SYSFUZZ, or have I misunderstood something?

2025-03-04 17:09 UTC, definitelyprobably commented on iso_defs.apln
> +    IntegerTolerance←1E¯14 ⍝ aka SYSFUZZ
Well, for 10.2.1 Join Along an Axis: (pp.137-8) `Z←A ,[K] B`:

![Screenshot from 2025-03-04 16-23-46](https://github.com/user-attachments/assets/bfe91c7e-6593-49e8-8e4e-e1d23ea11496)

Which implies that integer-tolerance is a parameter (it's also listed in the index on p.268 as an "implementation parameter"), and its use in axis here _does_ suggest it is our SYSFUZZ. But the issue is that integer-tolerance as a parameter is also used in lots of places via the definition of near-integer:

![Screenshot from 2025-03-04 16-22-22](https://github.com/user-attachments/assets/690521c5-c4f0-4119-9f7d-c1223503a5ad)

For example (p.91):

![Screenshot from 2025-03-04 16-34-09](https://github.com/user-attachments/assets/a5f18842-d2ee-4045-b6f6-2b8ccbaac450)

I would have liked the standard to be clearer (but maybe I'm just not used to reading standards), but, regardless, we don't appear to be in standards-conformance wrt our use of SYSFUZZ:

```
      K←1+1e¯10
      ⎕CT←1e¯11
      K=1
0
      1 2 ,[K] 3 4
1 3
2 4
      K○1
DOMAIN ERROR
      K○1
       ∧
```
According to the standard, integer-tolerance as a parameter should be used in both places here, so I don't know how our quadct/SYSFUZZ match up to the standard :/ What we do practically have is a configurable ⎕CT (quadct) that is used almost everywhere and an immutable SYSFUZZ that is only ever used in axis (and maybe a few other places).

I guess you meant `IntegerTolerance` to be the SYSFUZZ value that we use in axis? In which case it's probably best we call it `SYSFUZZ` and then make the comment say something like: this is the integer-tolerance value used in axis, but we are not in standards conformance as this is not used universally as THE integer-tolerance parameter (as the standard indicates it should be) -- this SYSFUZZ value is only used for axis.

At least, assuming I've read the standard correctly...

2025-03-05 07:36 UTC, pmikkelsen commented on iso_defs.apln
> +    IntegerTolerance←1E¯14 ⍝ aka SYSFUZZ
I think you are right, but I would prefer if the iso_defs namespace only contained definitions from the standard, and not SYSFUZZ for example. The places where we are non-conforming should in my opinion just have model function + comments explaining what we do instead, and then not use the IntegerTolerance variable.

iso_defs is meant to be a source of constants/functions implementing exactly what is in the standard. And for that, the "correct" value for IntegerTolerance is in the case of the DyalogAPL interpreter, the value of SYSFUZZ.

One could argue that if A○B checks if A is integer using ⎕CT instead of using integer-tolerance, that is a bug?

2025-03-05 16:39 UTC, definitelyprobably commented on iso_defs.apln
> +    IntegerTolerance←1E¯14 ⍝ aka SYSFUZZ
OK, after a bit more investigation I think I understand what's going on.

First, my example was wrong. **Join Along an Axis** (section 10.2.1, p.137) was a bad example because it works with non-integral inputs too. So, actually, I think it is ok. The Circular Functions are correctly ignoring  ⎕CT and using SYSFUZZ:
```
      K←1+1e¯11
      ⎕CT←1e¯10
      K=1                 ⍝ K is integral with comparison-tolerance...
1
      K○1                 ⍝ ...but not integer-tolerance (SYSFUZZ)
DOMAIN ERROR
      K○1
       ∧
```
The standard says this. In section 5.3.8 Sessions (p.30):

> **Note**: _A user interacts with an APL system through a session, an abstraction that represents a
> hypothetical machine capable of carrying out the evaluation sequences in the International Standard_.

and later within that section says (p.32):

> **System-Parameter**: Any of **comparison-tolerance**, **random-link**, **print-precision**,
> **index-origin**, or **latent-expression**.

Then in section 5.3.10 Systems, on p.34:

>**– Comparison-Tolerance-Limit**: The largest **real-number** permitted by the
>    implementation for the system parameter **comparison-tolerance**.
>**– Integer-Tolerance**: A **real-number** not greater than **comparison-tolerance-limit**
>    used to determine whether a given number is to be considered integral.
>**– Real-Tolerance**: A **nonnegative-number** not greater than **comparison-tolerance-
>    limit** used to determine whether a given number is to be considered real.

So, it's not really clear to me what exactly a system-parameter is. Comparison-tolerance is a system-parameter within a session; but integer-tolerance and real-tolerance are parameters within a system??

But nonetheless, I think what's going on is that what we call SYSFUZZ is the implementation of both the integer-tolerance and real-tolerance values that are defined in the standard. Here is the list of all primitives and what they depend on:

- 7.1.5 Floor: comparison-tolerance
- 7.1.6 Ceiling: comparison-tolerance
- 7.1.12 Not: integer-tolerance (via near-boolean)
- 7.2.5 Maximum: real-tolerance (via near-real)
- 7.2.6 Minimum: real-tolerance (via near-real)
- 7.2.9 Residue: comparison-tolerance
- 7.2.11 Circular Functions: integer-tolerance (via near-integer)
- 7.2.12 And/LCM: comparison-tolerance
- 7.2.12 Or/GCD: comparison-tolerance
- 7.2.14 Nand: integer-tolerance (via near-boolean)
- 7.2.15 Nor: integer-tolerance (via near-boolean)
- 7.2.16 Equal: comparison-tolerance
- 7.2.17 Less than: real-tolerance (via near-real) and comparison-tolerance
- 7.2.18 Less than or equal to: real-tolerance (via near-real) and comparison-tolerance
- 7.2.19 Not equal: comparison-tolerance
- 7.2.20 Greater than or equal to: real-tolerance (via near-real) and comparison-tolerance
- 7.2.21 Greater than: real-tolerance (via near-real) and comparison-tolerance
- 8.2.3 Index Generator: integer-tolerance (via near-integer)
- 8.3.1 Reshape: integer-tolerance (via near-integer)
- 9.2.1 Reduction: integer-tolerance (via valid-axis)
- 9.2.2 Scan: integer-tolerance (via valid-axis)
- 9.2.3 N-wise Reduction: integer-tolerance (via valid-axis)
- 9.3.4 Rank operator deriving monadic function: integer-tolerance (via near-integer)
- 9.3.5 Rank operator deriving dyadic function: integer-tolerance (via near-integer)
- 10.1.1 Roll: integer-tolerance (via near-integer)
- 10.1.2 Grade Up: real-tolerance (via near-real)
- 10.1.3 Grade Down: real-tolerance (via near-real)
- 10.1.4 Reverse: integer-tolerance (via valid-axis)
- 10.1.5 Monadic Transpose: integer-tolerance (via Index Generator)
- 10.1.8 Unique: comparison-tolerance
- 10.2.1 Join Along an Axis: integer-tolerance (via near-integer)
- 10.2.2 Index of: comparison-tolerance
- 10.2.3 Member of: comparison-tolerance
- 10.2.4 Deal: integer-tolerance (via near-integer)
- 10.2.5 Replicate: integer-tolerance (via near-integer) and comparison-tolerance
- 10.2.6 Expand: integer-tolerance (via valid-axis) and comparison-tolerance
- 10.2.7 Rotate: integer-tolerance (via near-integer) and comparison-tolerance
- 10.2.9 Representation: comparison-tolerance
- 10.2.10 Dyadic Transpose: integer-tolerance (via near-integer) and comparison-tolerance
- 10.2.11 Take: integer-tolerance (via near-integer)
- 10.2.12 Drop: integer-tolerance (via integer-array-nearest-to) and comparison-tolerance
- 10.2.14 Indexed Reference: integer-tolerance (via near-integer)
- 10.2.15 Indexed Assignment: integer-tolerance (via near-integer) and comparison-tolerance
- 10.2.16 Without: comparison-tolerance
- 10.2.22 Pick: integer-tolerance (via near-integer)
- 10.2.25 Disclose with Axis: integer-tolerance (via valid-axis) [Note: actually says valid-axis-of, which is nowhere defined, and references non-existing A]
- 10.2.27 Enclose with Axis: should be integer-tolerance (via valid-axis) but never actually says that!

(Caveat: some of these just use comparison-tolerance by saying do some operation with it set to zero; and I may also have missed some things...)

Everywhere that is mentioned integer-tolerance or real-tolerance, we use SYSFUZZ. So, as an example for integer-tolerance let's use Not, for real-tolerance let's use Maximum, and for comparison-tolerance let's use Equal:
```
      ⎕CT←1e¯10
      a←1+1e¯11         ⍝ a is outside of integer-tolerance (SYSFUZZ) but within comparison-tolerance
      z←1j1e¯11         ⍝ z is outside of real-tolerance (SYSFUZZ) but within comparison-tolerance
      B←1+1e¯9          ⍝ B is outside of both integer-tolerance (SYSFUZZ) and comparison-tolerance
      W←1j1e¯9          ⍝ W is outside of both real-tolerance (SYSFUZZ) and comparison-tolerance

      1 = a B , z W     ⍝ Equals works to comparison tolerance. Both B and W are outside of comparison-tolerance
1 0 1 0

     ~a                 ⍝ Not works to integer-tolerance (SYSFUZZ) and a is outside of this
DOMAIN ERROR
      ~a
      ∧

      1⌈z               ⍝ Maximum works to real-tolerance (SYSFUZZ) and z is outside of this
DOMAIN ERROR
      1⌈z
       ∧
```
This does lead to the strange position where `a=1` but `~a` domain errors, but that is what the standard says.

So, I think it all looks OK. I think you're right in that we should refer to the standard (maybe mention real-tolerance too?) and we can use integer-tolerance (and real-tolerance) to test whether the primitives are doing what they're supposed to.

Tangent: we should really give a show'n'tell on this as I bet nobody knows all of that. I certainly didn't.

2025-03-20 17:27 UTC, pmikkelsen reviewed
Todo:
- [ ] More comments
- [x] Rename the new run variations
- [x] "static" tests without model function
- [x] Skip complex on version < 20.0
- [ ] Check code coverage

2025-03-24 10:50 UTC, pmikkelsen commented
@sloorush I have committed the changes we agreed upon at the internal meeting last week. Feel free to merge when you are happy, and then we can raise an issue and do a big auto-formatting change for the entire repository later.

2025-03-24 16:44 UTC, merged